---
- hosts: loadbalancer, webservers
  gather_facts: True
  tasks:

    - name: System OS Distro and verison via Ansible facts
      debug: msg={{ ansible_distribution, ansible_distribution_version }}

    - name: Disable Selinux on LB and Web Servers
      selinux:
        state: disabled
