---
- name: HAProxy Deployment for multiple web server cluster
  hosts: loadbalancer

  vars:
    lb_ip: 'ansible-lb 192.168.88.56:80'
    web01_ip: 'ansible-srva 192.168.88.49:80'
    web02_ip: 'ansible-srvb 192.168.88.55:80'

  become: yes

  tasks:
    - name: Latest version of all requared packages for HAProxy servers installation
      yum:
        name:
          - firewalld
          - haproxy
        state: latest

#    - name: Configure haproxy
#      copy:
#        src: /home/tkadmin/tk-projectx/files/haproxy.cfg
#        dest: /etc/haproxy/haproxy.cfg

    - name: Confgure haproxy
      template:
        src: /home/tkadmin/tk-projectx/templates/haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Firewalld enabled and running
      service:
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits for httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: HAProxy enabled and running
      service:
        name: haproxy
        enabled: true
        state: started         
