---
- name: Web Server Deployment
  hosts: webservers
  become: yes

  tasks:
    - name: Latest version of all requared packages for Web servers installation
      yum:
        name:
          - firewalld
          - httpd
          - php
          - php-mysql
        state: latest

    - name: Firewalld enabled and running
      service: 
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits for httpd service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service:
        name: httpd
        enabled: true
        state: started         

    - name: Customize default index.html page 
      copy:
        content: "<h1> Text Kernel test page ...</h1>"
        dest: /var/www/html/index.html 
        mode: 0644

    - name:  info.php  page is installed
      copy:
        src: /home/tkadmin/tk-projectx/files/info.php
        dest: /var/www/html/info.php 
